easy_admin:
    site_name: Conference book

    design:
      menu:
        - { route: 'homepage', label: 'Back to the website', icon: 'home'}
        - { entity: 'Conference', label: 'Conference', icon: 'map-maker'}
        - { entity: 'Comment', label: 'Comments', icon: 'comments'}

    entities:
        Conference:
            class: App\Entity\Conference
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image' , 'base_path': '/uploads/photos', 'lable': 'Photo'}
                    - { property: 'createdAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'conference'}
                    - { property: 'createdAt', type: datetime, type_option: { attr: {readonly: true } } }
                    - 'author'
                    - { property: 'email', type: 'email'}
                    - text